
import React, { useContext } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import MyScene from "~/components/SceneWrapper";
import ClientSizeContext from "~/utils/ClientSize";

const Home: NextPage = () => {
  const { width, height } = useContext(ClientSizeContext);

  console.log("width", width);



  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
      <MyScene color="red" />
      </main>
    </>
  );
};

export default Home;
